Tour manager issue26
titancamp/travely pull request #101
Opened 2021-02-13 14:35 UTC by vardkhachatryan96

2021-02-15 19:28 UTC, HAghajanyan-ST requested changes
Most of comments are repeated.

Special thank you for all comments :)

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Common/Extend/Str.cs
> +            return string.IsNullOrWhiteSpace(str);
Why ? :D

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Repository.EfCore.MsSql/Repositories/BookingRepository.cs
> +        public async Task<List<BookingEntity>> GetAll(int tourId)
Where is no need to make method async you can just return Task from method below

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Repository.EfCore.MsSql/Repositories/ClientRepository.cs
> +        public async Task<List<TourClientEntity>> GetAll(int tourId)
Remove async/await

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Repository.EfCore.MsSql/Repositories/TourRepository.cs
> +        public async Task<IEnumerable<TourEntity>> GetAllFromToday()
Use Find from baserepository as it used in method above and remove async/await

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Implementation/BookingService.cs
> +            await this.bookingRepository.Add(BookingMapper.MapToSingle(booking));
just return Task, there is no need async/await

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Implementation/BookingService.cs
> +            await this.bookingRepository.Update(BookingMapper.MapToSingle(booking));
Same as comment above remove async/await

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Implementation/Mappers/BookingMapper.cs
> +    public class BookingMapper
Why you are not using AutoMapper ?

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Implementation/Mappers/ClientMapper.cs
> +    public class ClientMapper
Please use automapper

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Implementation/Mappers/TourMapper.cs
> +    public class TourMapper
Use AutoMapper

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Model/Booking.cs
> +        public List<string> Destinations { get; set; }
Please also add validation profile in this file for current model (Use FluentValidation)

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Model/Client.cs
> +    }
Add Validation

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Model/Tour.cs
> -		public List<Client> Clients { get; set; }
Add Validation

2021-02-15 19:28 UTC, HAghajanyan-ST commented on src/TourManager/TourManager.Service.Model/Validations/TourValidator.cs
>          public TourValidator()
Move to Model file

2021-02-17 12:24 UTC, grigor-yeghiazaryan approved these changes

2021-02-17 12:24 UTC, grigor-yeghiazaryan commented on src/TourManager/TourManager.Service.Implementation/TourService.cs
> +{
Let's remove these comments, they don't help, they only get in the way, right?

2021-02-17 12:24 UTC, grigor-yeghiazaryan commented on src/TourManager/TourManager.Service.Implementation/TourService.cs
> +
Not sure if it will work correctly, but we'll check later anyway

2021-02-17 12:24 UTC, grigor-yeghiazaryan commented on src/TourManager/TourManager.Service.Implementation/TourService.cs
> +
the same here, some logic is missing, let's skip it for now

2021-02-17 12:24 UTC, grigor-yeghiazaryan commented on src/TourManager/TourManager.Service.Model/Booking.cs
> +    /// <summary>
do we need these comments?

2021-02-17 13:00 UTC, HAghajanyan-ST approved these changes

2021-02-18 12:03 UTC, merged