Identity manager/models
titancamp/travely pull request #109
Opened 2021-02-14 12:46 UTC by GhTsovinar

2021-02-14 13:38 UTC, Soarc requested changes

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/Entities/User.cs
> +        public virtual ICollection<Employee> Employees { get; set; }
One user, one employee and one org :)

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/Entities/Employee.cs
> +        public string JobTitleId { get; set; }
This should not be Id

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/Entities/User.cs
> +        public int RoleId { get; set; }
Enum for roles. Not roleId

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/IBaseRepository.cs
> +        Task<TEntity> GetByConditionAsync(Expression<Func<TEntity, bool>> expression, CancellationToken cancaletionToken = default);
Remove still missing

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/IBaseRepository.cs
> +        Task<TEntity> GetByIdAsync(int id, CancellationToken cancaletionToken = default);
I beleive FindByIdAsync is better naming

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/IBaseRepository.cs
> +        Task<TEntity> GetByConditionAsync(Expression<Func<TEntity, bool>> expression, CancellationToken cancaletionToken = default);
This could be just FindAsync

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/IBaseRepository.cs
> +        IQueryable<TEntity> GetAll();
We can expose Query property instead of GetAll method

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/IBaseRepository.cs
> +        Task<TEntity> GetByIdAsync(int id, CancellationToken cancaletionToken = default);
fix typo `cancaletionToken ` -> `cancellationToken`

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/IUserRepository.cs
> +        Task<User?> GetUserByUsernameAsync(string username, CancellationToken cancaletionToken = default);
`FindByEmailAsync` is better naming

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Repository.Abstractions/IUserRepository.cs
> +        Task<bool?> CheckPasswordAsync(string username, string Password, CancellationToken cancaletionToken = default);
Remove this method

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Travely.IdentityManager.Repository.Model/Travely.IdentityManager.Repository.Model.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Remove this folder

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Travely.IdentityManager.Repository/BaseRepository.cs
> +                throw new ArgumentException("entity");
`throw new ArgumentException(nameof(entity));`

2021-02-14 13:38 UTC, Soarc commented on src/IdentityManager/Travely.IdentityManager.Repository/BaseRepository.cs
> +            Update(entity);
??

2021-02-14 13:38 UTC, GhTsovinar commented on src/IdentityManager/Repository.Abstractions/Entities/User.cs
> +        public virtual ICollection<Employee> Employees { get; set; }
done

2021-02-14 13:48 UTC, GhTsovinar commented on src/IdentityManager/Repository.Abstractions/Entities/Employee.cs
> +        public string JobTitleId { get; set; }
done

2021-02-14 14:05 UTC, GhTsovinar commented on src/IdentityManager/Repository.Abstractions/Entities/User.cs
> +        public int RoleId { get; set; }
done

2021-02-14 14:30 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.Repository/BaseRepository.cs
> +            Update(entity);
change to hard delete

2021-02-18 13:11 UTC, GRustamyan-ST approved these changes
I'm mergin you changes, but there are some minor issues in comments. Please fix them as well.

2021-02-18 13:11 UTC, GRustamyan-ST commented on src/IdentityManager/Packages.props
> +    <PackageReference Update="IdentityServer4.EntityFramework" Version="4.1.1" />
Please remove this package. We should not depend on it.

2021-02-18 13:11 UTC, GRustamyan-ST commented on src/IdentityManager/Repository.Abstractions/Entities/Agency.cs
> +        public int Status { get; set; }
Return type should be Status enumeration.

2021-02-18 13:15 UTC, merged