Added exception handling
titancamp/travely pull request #119
Opened 2021-02-16 12:44 UTC by VardanGhazaryan1997

2021-02-16 12:55 UTC, HAghajanyan-ST requested changes

2021-02-16 12:55 UTC, HAghajanyan-ST commented on Travely.Services.Common/CustomExceptions/BusinessLayerException.cs
> +    public class BusinessLayerException : Exception
Make this class abstract

2021-02-16 12:55 UTC, HAghajanyan-ST commented on Travely.Services.Common/CustomExceptions/DataLayerException.cs
> +	{
Same with this class (abstarct)

2021-02-16 12:55 UTC, HAghajanyan-ST commented on Travely.Services.Common/Middlewares/ExceptionHandlingMiddleware.cs
> +			throw new NotImplementedException();
Handler not implemented ? :D in suck cases or use abstract class with abstract method or just return Task.CompletedTask

2021-02-17 12:56 UTC, HAghajanyan-ST approved these changes

2021-02-22 14:00 UTC, HAghajanyan-ST approved these changes

2021-02-22 18:09 UTC, MariamMarti approved these changes

2021-02-23 06:53 UTC, merged