Merge master branch 'origin/master' into scheduler-manager
titancamp/travely pull request #244
Opened 2021-05-01 09:14 UTC by TGrigor

2021-05-03 09:40 UTC, anush1111 approved these changes

2021-05-04 14:31 UTC, Tavrizyan approved these changes

2021-05-06 16:41 UTC, GevorgMartirosyan requested changes

2021-05-06 16:41 UTC, GevorgMartirosyan commented on src/SchedulerManager/Travely.SchedulerManager.API/Properties/launchSettings.json
> -      "applicationUrl": "http://localhost:5300;https://localhost:5301"
please do not change the ports.

2021-05-06 16:41 UTC, GevorgMartirosyan commented on src/SchedulerManager/Travely.SchedulerManager.API/Startup.cs
> -                            .WithOrigins("http://localhost:3000", "https://travely.am");
Please do not change Infrastructure related statements.

2021-05-06 16:41 UTC, GevorgMartirosyan commented on src/SchedulerManager/Travely.SchedulerManager.API/Startup.cs
> +            //xx.StartJobAsync(new InformationJob(), new InformationJobParameter { TourName = "Enqueue Job" }).GetAwaiter().GetResult();
Please remove this.

2021-05-06 16:41 UTC, GevorgMartirosyan commented on src/SchedulerManager/Travely.SchedulerManager.API/Startup.cs
> +            //yy.StartJobAsync(new InformationJob(), TimeSpan.FromSeconds(5), new InformationJobParameter { TourName = "Scheduled Job" }).GetAwaiter().GetResult();
This also.

2021-05-06 16:41 UTC, GevorgMartirosyan commented on src/SchedulerManager/Travely.SchedulerManager.API/appsettings.json
> +    "ConnectionString": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=SchedulerDb;Integrated Security=True"
Please do not change this.

2021-05-06 16:41 UTC, GevorgMartirosyan commented on src/SchedulerManager/Travely.SchedulerManager.API/appsettings.json
> +    "ConnectionString": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=SchedulerDb;Integrated Security=True"
Please do not change this.

2021-05-07 13:40 UTC, GevorgMartirosyan approved these changes

2021-05-07 13:41 UTC, merged