Permissions and User model changes
titancamp/travely pull request #255
Opened 2022-01-11 13:20 UTC by Narine-Manukyan

Permissions and User model changes

2022-01-11 13:41 UTC, arttonoyan approved these changes, later dismissed

2022-01-13 16:02 UTC, GevorgMartirosyan commented on src/IdentityManager/IdentityClient/Authorization/TravelyAuthorizationMiddleware.cs
> +            // Իմանալ claim-ով permission-ը կարողնում են ուղարկել թե չէ հակառակ դեպքում բազայից կարդալ ստուգել
Please write all comments in English.

2022-01-13 16:03 UTC, GevorgMartirosyan requested changes

2022-01-13 16:03 UTC, GevorgMartirosyan commented on src/IdentityManager/IdentityClient/Authorization/TravelyAuthorizationMiddleware.cs
> +                // throw Exception
Please handle this case.

2022-01-29 11:57 UTC, arttonoyan submitted a review, later dismissed

2022-01-29 12:21 UTC, merged