Tour manager repos
titancamp/travely pull request #73
Opened 2021-01-26 19:31 UTC by ArturVah

2021-01-26 20:16 UTC, HAghajanyan-ST requested changes
Sent by mobile - excuse brevity & typo errors

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Context/TourContext.cs
> +
Please remove white spaces between rows

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Entities/Client.cs
> +        public long Id { get; set; }
Create BaseEntity and move Id to to that Class , also add CreatedAt and UpdatedAt fields in BaseEntity

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Entities/Tour.cs
> +        public string Description { get; set; }
Mark any optional field as nullable

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Repositories/GenericRepository.cs
> +            await Context.Set<TEntity>().AddAsync(entity);
Don't use AddAsync method , read method description for clarification ))

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Repositories/GenericRepository.cs
> +    public class GenericRepository<TEntity> : IRepository<TEntity> where TEntity : class
Don't mention Generic word in class naming

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Repositories/GenericRepository.cs
> +namespace Travely.TourManager.Repository.Repositories
Move this class to some common library because it can be used by any of our services (equipment, activities, etc)

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Repositories/GenericRepository.cs
> +            await Context.Set<TEntity>().AddRangeAsync(entities);
Same as AddAsync

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Repositories/GenericRepository.cs
> +            return Context.Set<TEntity>().Where(predicate);
Why you are not using async version ?

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Repositories/GenericRepository.cs
> +            return Context.Set<TEntity>().Where(predicate);
You must call ToList or ToArray to execute statement

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Readme.md
> +sudo docker-compose up
Why we need sudo ?

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Repositories/GenericRepository.cs
> +            Context.Set<TEntity>().Remove(entity);
You must call Context.SaveChanges() to apply on DB

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/Repositories/TourRepository.cs
> +        private TourContext _context;
You can make GenericRepository more generic and make also DbContext Type as argument to avoid keeping to copy of context in one repository

2021-01-26 20:16 UTC, HAghajanyan-ST commented on src/TourManager/Repository/docker-compose.yml
> +    image: postgres
Connection String is MySql , ef provider is MsSql and in docker compose you have defined postgreSql )))

2021-01-26 20:26 UTC, TomaCode commented on src/TourManager/Repository/Configurations/ClientConfiguration.cs
> +    class ClientConfiguration : IEntityTypeConfiguration<Client>
I'd prefer writing the visibility explicitly. internal class smth...., but your decision anyways.

2021-01-26 20:27 UTC, TomaCode commented on src/TourManager/Repository/Configurations/TourClientConfiguration.cs
> +
excessive linebreak

2021-01-26 20:32 UTC, TomaCode commented on src/TourManager/Api/Startup.cs
>  {
no "Travely" namespaces anymore. rebase and follow the constraint.

2021-01-26 20:36 UTC, TomaCode commented on src/TourManager/Repository/Repositories/GenericRepository.cs
> +            await Context.Set<TEntity>().AddAsync(entity);
shouldn't here be a return statement?

2021-01-27 20:59 UTC, TomaCode requested changes

2021-01-27 20:59 UTC, TomaCode commented on src/TourManager/Repository/Entities/Booking.cs
> +    public class Booking
right now I'm a little bit confused regarding the model naming. I'd name the repo entities with some name like BookingEntity, and model name would be Booking, which is more practical. Naming it BookinModel, or BookingData creates artificial misunderstanding tho. If possible please change 🤔

2021-02-10 16:02 UTC, closed without merging