Identity manager/solution config
titancamp/travely pull request #76
Opened 2021-01-29 06:21 UTC by TadevosStepanyan

created separate solution for Identity manager & done changes for file structures & added config files

2021-01-29 11:40 UTC, GRustamyan-ST requested changes

2021-01-29 11:40 UTC, GRustamyan-ST commented on src/IdentityManager/Directory.Build.props
> +    <Authors>ServiceTitanCamp Identity team</Authors>
ServiceTitanCamp Identity team-> Titan Camp

2021-01-29 11:40 UTC, GRustamyan-ST commented on src/IdentityManager/Directory.Build.props
> +    <Company>ServiceTitanCamp</Company>
ServiceTitanCamp -> Titan Camp

2021-01-29 11:40 UTC, GRustamyan-ST commented on src/IdentityManager/IdentityManager.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Please move SLN file to repository root. On long period this will save good amount of time of launching project.

2021-01-29 11:40 UTC, GRustamyan-ST commented on src/IdentityManager/Directory.Build.props
> +    <ArtifactsDir>$(SolutionDir)artifacts</ArtifactsDir>
I case of this repo, we can also add service name in output path. So we can introduce ServiceName variable and add it to aritfacts path.
```
<ServiceName>identitymanager</ServiceName>
 <ArtifactsDir>$(SolutionDir)artifacts/$(ServiceName)</ArtifactsDir>
```

2021-01-29 11:40 UTC, GRustamyan-ST commented on src/IdentityManager/src/Directory.Build.props
> +    <BaseIntermediateOutputPath>$(SolutionDir)artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
Use `ArtifactsDir` variable` $(SolutionDir)artifacts\obj\$(MSBuildProjectName)` -> `$(ArtifactsDir)\obj\$(MSBuildProjectName)`

2021-01-29 11:40 UTC, GRustamyan-ST commented on src/IdentityManager/src/Directory.Build.props
> +    <OutputPath>$(SolutionDir)artifacts\bin</OutputPath>
Same here

2021-01-29 11:40 UTC, GRustamyan-ST commented on src/IdentityManager/src/IdentityManager.API/IdentityManager.API.csproj
>    </PropertyGroup>
Remove extra src and identityManager. Final path should be `src/IdentityManager/WebApi/IdentityManager.WebApi.csproj`

In c# abbreviations use CamelCase as wekk. `API`->`Api`

2021-02-01 10:47 UTC, TadevosStepanyan commented
@GRustamyan-ST changes has been done considering the comments

2021-02-01 13:04 UTC, GRustamyan-ST requested changes
One more thing: Since we don't want to mess with other teams services in repository
Please move `Directory.Build.props`, `Directory.Build.targets`, `Packages.props` and `version.json` to IdentityManager folder.

2021-02-01 13:26 UTC, GRustamyan-ST approved these changes

2021-02-01 13:26 UTC, merged