Identity manager/webapi identity
titancamp/travely pull request #81
Opened 2021-02-02 06:45 UTC by Astgh000

2021-02-03 09:00 UTC, GRustamyan-ST requested changes
I don't see any API endpoints related to Company, List/Add/Remove users/employees.
Registration Endpoint should contain Company data as well. Please sync with @GhTsovinar for exact fields.

2021-02-03 10:24 UTC, Astgh000 commented on src/IdentityManager/IdentityManager.API/Controllers/AuthenticationController.cs
> +    public class AuthenticationController : ControllerBase
ok

2021-02-03 11:44 UTC, GArik commented on src/IdentityManager/IdentityManager.API/Controllers/AuthenticationController.cs
> +        public async Task<ActionResult> RefreshToken([FromBody] Models.AuthResponse refreshRequest)
You probably wanted to add someone else to this discussion :)

2021-02-03 23:52 UTC, TadevosStepanyan commented on src/IdentityManager/IdentityManager.API/Dockerfile
> +#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
done

2021-02-18 14:40 UTC, GRustamyan-ST requested changes

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +        public async Task<IActionResult> RegisterAsync([FromBody] RegisterViewModel model)
Please use Task<ActionResult<T>> as response type everywhere.
Also all actions are missing CancellationTokens. Please add them as well.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +                    return Ok(result);
After you change response type to ActionResult<T>, return `result `itself instead `Ok(result)` . Do this in all actions.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +        public async Task<IActionResult> LoginAsync([FromBody] LoginViewModel model)
We don't need this action, since Id4 server has its own Authentication endpoing.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +        public async Task<IActionResult> ResetPassword([FromForm] ResetPasswordViewModel model)
This should be [FromBody], not [FromForm].

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +            return Ok(await _authenticationService.GetUserByUserName(username));
You don't need wrap reponses in `Ok` function call. Remove that call.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +        public async Task<ActionResult<UserResponseModel>> GetUserByUserNameAsync(string username)
Why we need this API endpoint?

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +        public async Task<ActionResult<AgencyResponseModel>> GetAgencyByNameAsync(string agencyName)
Why we need this endpoint?

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +        public async Task<ActionResult<UserResponseModel>> GetUserByIdAsync(int id)
Lets move `GetUserByIdAsync`, `GetUsersAsync` to separate `UsersController`. Also, please make endpoints restfull, So we

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +        /// <summary>
Missing endpoint, that will allow users created by Admin sign-in first time.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Controllers/AccountController.cs
> +        public async Task<ActionResult<AgencyResponseModel>> GetAgencyByIdAsync(int id)
Missing endpoints, that will allow admin manage employees - adding new employee to agency, remove/suspend existing employee, edit existing employee Data (Name, job-title etc)

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        public async Task<string> GenerateAccessToken(IdentityUser user)
This will handle Id4 server. Please remove.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        public async Task<Models.AuthResponse> GenerateAccessToken(RegisterViewModel model)
This will handle Id4 server. Please remove.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        public async Task<Models.AuthResponse> LoginUserAsync(LoginViewModel model)
This will handle Id4 server. Please remove.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        public AuthenticationService(IUserRepository userRepository, IUnitOfWork unitOfWork,
Please add cancellation tokens to all service methods

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        public async Task<Models.AuthResponse> RefreshToken(Models.AuthResponse model)
This will handle Id4 server. Please remove.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        private async Task<IdentityUser> GetUserFromAccessToken(string accessToken)
We don't need this method.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        private async Task<bool> ValidateRefreshToken(IdentityUser user, string refreshToken)
This will handle Id4 server. Please remove.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +            return Mapper.Map<IEnumerable<UserResponseModel>>(await _userRepository.GetAll());
Use Automapper's ProjectTo method, so we don't materialize repository objects.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        public async Task<AgencyResponseModel> GetAgencyByName(string agencyName)
Remove

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Models/AuthResponse.cs
> +        public string AccessToken { get; set; }
We should not return Id4 specific info (like AccessToken or RefreshToken ) from our endpoint. That will do Id4 enpoint itself.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Models/ResetPasswordViewModel.cs
> +    public class ResetPasswordViewModel
Remove

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Models/RegisterViewModel.cs
> +    public class RegisterViewModel
I suppose this model is used, when new Agency is registered (with new user itself). 
Please check with mocks, which fields we require. There should be much more fields.

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Models/Response/AgencyResponseModel.cs
> +        public int Id { get; set; }
Please match fields with mocks (or db entities)

2021-02-18 14:40 UTC, GRustamyan-ST commented on src/IdentityManager/WebApi/Models/Response/UserResponseModel.cs
> +        public string JobTitleId { get; set; }
Please match fields with DbEntities. Also i'm not seeing Employee data

2021-02-21 11:21 UTC, Soarc requested changes

2021-02-21 11:21 UTC, Soarc commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +            var user = await _userRepository.FindByEmailAsync(email, ct);
Here should be logic  with Generating token and storing it

2021-02-21 11:21 UTC, Soarc commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +        public async Task<ActionResult<ResultViewModel>> RegisterUserAsync(RegisterViewModel model, CancellationToken ct)
Service layer should not return ActionResult

2021-02-21 11:21 UTC, Soarc commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +            var result = await _userManager.CreateAsync(user, model.Password);
We are not using UserManager. We need custom implementation.

2021-02-21 11:21 UTC, Soarc commented on src/IdentityManager/WebApi/Identity/AuthenticationService.cs
> +            return Mapper.Map<IEnumerable<UserResponseModel>>(await _userRepository.GetAll().ToListAsync());
Use  automapper's Queryable ProjectTo extension methods

2021-02-21 11:21 UTC, Soarc commented on src/IdentityManager/WebApi/Identity/IAuthenticationService.cs
> +        Task<ActionResult<ResultViewModel>> RegisterUserAsync(RegisterViewModel model, CancellationToken ct);
Service layer should not return ActionResult

2021-02-21 11:21 UTC, Soarc commented on src/IdentityManager/WebApi/Models/ApplicationUser.cs
> +    public class ApplicationUser: IdentityUser
What is this? We should not have this model.

2021-03-04 21:36 UTC, Soarc approved these changes

2021-03-04 21:36 UTC, merged