Identity manager models
titancamp/travely pull request #84
Opened 2021-02-04 17:09 UTC by GhTsovinar

2021-02-08 10:06 UTC, GRustamyan-ST requested changes

2021-02-08 10:06 UTC, GRustamyan-ST commented on src/IdentityManager/Travely.IdentityManager.Repository/UnitOfWork.cs
> +        public IEmployeeRepository EmployeeDataRepository
See comment on IUnitOfWork

2021-02-09 11:57 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.IRepository/Travely.IdentityManager.IRepository.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
done

2021-02-09 14:23 UTC, GhTsovinar commented on src/IdentityManager/Packages.props
> +    <PackageReference Update="IdentityServer4.EntityFramework" Version="4.1.1" />
removed it

2021-02-09 14:24 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.IRepository/IAgencyRepository.cs
> +namespace Travely.IdentityManager.IRepository
done

2021-02-09 14:41 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.Repository/BaseRepository.cs
> +    public class BaseRepository<TEntity, U> : IBaseRepository<TEntity> where TEntity : class, new()
done

2021-02-09 14:43 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.Repository/UnitOfWork.cs
> +        public UnitOfWork(DbContext dbContext)
done

2021-02-09 15:01 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.Repository.Model/AppEntities/Agency.cs
> +            Employees = new HashSet<Employee>();
done

2021-02-09 19:47 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.IRepository/IBaseRepository.cs
> +        Task<TEntity> GetByIdAsync(int id);
done

2021-02-10 13:44 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.IRepository/IBaseRepository.cs
> +    public interface IBaseRepository<TEntity> where TEntity : class, new()
needs to be discussed

2021-02-10 13:44 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.IRepository/IUnitOfWork.cs
> +        IUserRepository UserRepository { get; }
needs to be discussed

2021-02-10 13:44 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.Repository/UnitOfWork.cs
> +        public IEmployeeRepository EmployeeDataRepository
needs to be discussed

2021-02-14 12:42 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.IRepository/IBaseRepository.cs
> +    public interface IBaseRepository<TEntity> where TEntity : class, new()
done

2021-02-14 12:42 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.IRepository/IUnitOfWork.cs
> +        IUserRepository UserRepository { get; }
done

2021-02-14 12:42 UTC, GhTsovinar commented on src/IdentityManager/Travely.IdentityManager.Repository/UnitOfWork.cs
> +        public IEmployeeRepository EmployeeDataRepository
done

2021-02-14 12:47 UTC, closed without merging

2021-02-14 12:47 UTC, GhTsovinar commented
created another branch